Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace MVCProject.Controllers
{
    [AllowAnonymous]
    public class AccountController : Controller
    {
        
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(tbl_User user)
        {
            SampleMVCEntities db = new SampleMVCEntities();
            var check = db.tbl_User.Where(x => x.UserName == user.UserName && x.Password == user.Password).Count();

            if (check > 0)
            {
                FormsAuthentication.SetAuthCookie(user.UserName, false);
                return this.RedirectToAction("List","Home");
            }
            else
            {
                return View();
            }
        }

        

    }
}

Controllers/DeptController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCProject.Controllers
{
    public class DeptController : Controller
    {
        // GET: Dept
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            SampleMVCEntities db = new SampleMVCEntities();
            List<tbl_User> user = db.tbl_User.ToList();
            return Json(new { data= user},JsonRequestBehavior.AllowGet);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Rotativa;
namespace MVCProject.Controllers
{

    public class HomeController : Controller
    {
        
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        
        [HttpGet]
        [Authorize(Roles = "User,Admin")]
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(tbl_User user)
        {
            if (ModelState.IsValid)
            {
                using (SampleMVCEntities db = new SampleMVCEntities())
                {
                    user.Role = "User";
                    db.tbl_User.Add(user);
                    db.SaveChanges();
                }

                return RedirectToAction("List");
            }
            else
            {
                return View();
            }

        }
        [HttpGet]
        public ActionResult List()
        {
            SampleMVCEntities db = new SampleMVCEntities();
            List<tbl_User> list = db.tbl_User.ToList();
            return View(list);
        }

        [HttpPost]
        public ActionResult List(string textSearch)
        {
            SampleMVCEntities db = new SampleMVCEntities();
            List<tbl_User> usr = db.tbl_User.ToList();

            if (textSearch != null)
            {
                usr = db.tbl_User.Where(x => x.UserName.Contains(textSearch) || x.Email.Contains(textSearch) ||
                    x.Gender.Contains(textSearch)).ToList();
            }
            return View(usr);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            SampleMVCEntities db = new SampleMVCEntities();
            tbl_User user = db.tbl_User.Find(id);
            ViewBag.skills = db.tbl_skills.ToList();
            user.Gender = user.Gender.Trim();
            return View(user);
        }

        [HttpPost]
        public ActionResult Edit(tbl_User user, HttpPostedFileBase postedFile)
        {
            SampleMVCEntities db = new SampleMVCEntities();
            string filename;
            if (user.UserImage != null)
            {
                filename = Path.GetFileNameWithoutExtension(user.UserImage.FileName);
                string extension = Path.GetExtension(user.UserImage.FileName);
                user.imagePath = "~/images/" + filename + extension;
                filename = Path.Combine(Server.MapPath("~/images/"), filename + extension);
                //saves image in folder
                user.UserImage.SaveAs(filename);
            }
            else
            {
                //user.imagePath = "~/images/img.png";
                //filename = Path.Combine(Server.MapPath("~/images/"), "img.png");
                //bool isExist = System.IO.File.Exists(user.imagePath);
                ////user.UserImage.SaveAs(filename);
            }
            user.Role = "User";
            db.Entry(user).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            SampleMVCEntities db = new SampleMVCEntities();
            tbl_User user = db.tbl_User.Find(id);
            return View(user);
        }

        public ActionResult Delete(int id)
        {
            SampleMVCEntities db = new SampleMVCEntities();
            tbl_User user = db.tbl_User.Find(id);
            db.tbl_User.Remove(user);
            db.SaveChanges();
            return RedirectToAction("List");
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return this.RedirectToAction("Login", "Account");
        }


        public ActionResult PrintAll()
        {
            var print = new ActionAsPdf("List");
            return print;
        }
    }
}

Views/Dept/Index.cshtml
@model IEnumerable<MVCProject.tbl_skills>

@{
    ViewBag.Title = "Index";
}

<h2>User List using Jquery Datatable</h2>
<table id="UserList" class="display table table-striped table-bordered mt-4" style="width:100%">
    <thead>
        <tr>
            <th>User Id</th>
            <th>User Name</th>
            <th>Email</th>
            <th>Gender</th>
            <th>Skills</th>
            <th>Photo</th>
            <th>Role</th>
            <th>Action</th>
        </tr>
    </thead>
</table>
<div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Modal Heading</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                Modal body..
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>

Views/Home/Delete.cshtml
@model MVCProject.tbl_User

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tbl_User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "List")
        </div>
    }
</div>

Views/Home/Details.cshtml
@model MVCProject.tbl_User

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>tbl_User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.UserId }) |
    @Html.ActionLink("Back to List", "List")
</p>

Views/Home/Edit.cshtml
@model MVCProject.tbl_User

@{
    ViewBag.Title = "Edit";
}

<br/><br/><br/>
@using (Html.BeginForm("Edit", "Home", FormMethod.Post, new { @class = "form-horizontal", enctype="multipart/form-data" }))
{
    <div class="container">
        <div class="row">
            <div class="col-md-4" id="imgeDiv">
                @if (!string.IsNullOrEmpty(Model.imagePath))
                {
                    <img src="@Url.Content(Model.imagePath)" class="img-responsive" height="250" width="250"/>
                }
                <input type="file" id="upload" name="UserImage"/>
            </div>
            <div class="col-md-8">
                <div class="form-group">
                    @Html.HiddenFor(Model => Model.UserId)

                    @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                   
                    @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <label class="radio-inline">
                            @Html.RadioButtonFor(model => model.Gender, "Male")
                            Male
                        </label>
                        <label class="radio-inline">
                            @Html.RadioButtonFor(model => model.Gender, "Female")
                            Female
                        </label>
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("Skills", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div>
                            @foreach (var item in ViewBag.skills)
                            {
                                <input id="@item.id" type="checkbox" name="@item.id" value="@item.id" />
                                <label for="@item.id">
                                    @item.name
                                </label>

                            }
                        </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control datepicker" } })
                        @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Update" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

Views/Home/List.cshtml
@model IEnumerable<MVCProject.tbl_User>

@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Register")
    @Html.ActionLink("Print", "PrintAll")
</p>
@using (Html.BeginForm("List","Home",FormMethod.Post))
{
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4 form-group">
                <input type="text" id="textSearch" name="textSearch" class="form-control" />
            </div>
            <div class="col-md-4 form-group">
                <button type="submit" class="btn btn-success">Search</button>
            </div>
        </div>
    </div>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DOB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Role)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.UserId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.UserName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Email)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Password)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Gender)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DOB)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Role)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.UserId }) |
        @Html.ActionLink("Details", "Details", new { id = item.UserId }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.UserId })
    </td>
</tr>
    }

</table>

Views/Home/Register.cshtml
@model MVCProject.tbl_User

@{
    ViewBag.Title = "Register";
}

<head>
    <link href="~/css/Register.css" rel="stylesheet" />
</head>
<body>
    <div id="registration">
        <div class="row">
            <div class="col-md-6" id="registerForm">
                @using (Html.BeginForm("Register", "Home", FormMethod.Post))
                {
                <form class="form-horizontal">
                    <h2>Registartion Form</h2>
                    <div class="form-group">
                        <div class="col-md-12">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">
                                        <span class="fa fa-user"></span>
                                    </span>
                                </div>
                                @Html.EditorFor(m => m.UserName, "", new { htmlAttributes = new { @class = "form-control",@placeholder = "Username" } })
                                @Html.ValidationMessageFor(m => m.UserName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">
                                        <span class="fa fa-envelope"></span>
                                    </span>
                                </div>
                                @Html.EditorFor(m => m.Email, "", new { htmlAttributes = new { @class = "form-control", @placeholder = "Email" } })
                                @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">
                                        <span class="fa fa-lock"></span>
                                    </span>
                                </div>
                                @Html.EditorFor(m => m.Password, "", new { htmlAttributes = new { @class = "form-control", type = "password", @placeholder = "*********" } })
                                @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <label class="radio-inline">
                                    @Html.RadioButtonFor(model => model.Gender, "Male", new { @name = "gender"})
                                    @*<input type="radio" id="male" name="Gender" value="Male" checked="@male" />*@
                                    Male
                                </label>
                                <label class="radio-inline">
                                    @Html.RadioButtonFor(model => model.Gender, "Female", new { @name = "gender"})
                                    @*<input type="radio" id="female" name="Gender" value="Female" checked="@female" />*@
                                    Female
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12" id="buttonDev">
                            <button type="submit" class="btn btn-success">Register</button>
                        </div>
                    </div>
                </form>
                }
            </div>
            <div class="col-md-6" id="registerImage">
                <img src="~/images/desktop.png" class="img-responsive" />
            </div>
        </div>
    </div>
</body>



@*@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>tbl_User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/library/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.dataTables.min.css" rel="stylesheet" />
    <link href="~/library/bootstrap/bootstrap-datepicker.min.css" rel="stylesheet" />
    @*<link href="~/library/fontawsome/font-awesome.min.css" rel="stylesheet" />*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav"></ul>
                </div>
            </div>
        </div>*@

    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        @Html.ActionLink("CodeX", "", "", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navb">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navb">
            <ul class="navbar-nav mr-auto">
                @if (User.Identity.IsAuthenticated == false)
                {
                    <li class="nav-item"><a href="" class="nav-link">Home</a></li>
                }
                @if (User.Identity.IsAuthenticated == true)
                {
                    if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item"><a href="" class="nav-link">About Us</a></li>
                        <li class="nav-item"><a href="" class="nav-link">Contact Us</a></li>
                    }

                    <li class="nav-item">@Html.ActionLink("User List", "List", "Home", new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Register", "Register", "Home", new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Skill", "Index", "Dept", new { @class = "nav-link" })</li>

                }

            </ul>
            <ul class="navbar-nav ml-auto">

                @if (User.Identity.IsAuthenticated == true)
                {
                    <li class="nav-item">@Html.ActionLink("Logout", "Logout", "Home", new { @class = "nav-link" })</li>
                    <li class="nav-item text-info">@User.Identity.Name</li>
                }
                @if (User.Identity.IsAuthenticated == false)
                {
                    <li class="nav-item">@Html.ActionLink("Login", "Login", "Account", new { @class = "nav-link" })</li>
                }

            </ul>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.print.min.js"></script>

    <script src="~/library/jquery/popper.min.js"></script>
    <script src="~/library/bootstrap/bootstrap.min.js"></script>
    <script src="~/library/bootstrap/bootstrap-datepicker.min.js"></script>
    <script src="~/library/jquery/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/custom.js"></script>
</body>
</html>